"""Test

Revision ID: 1c91125a1aa7
Revises: 2a501fcdf5a0
Create Date: 2023-10-31 21:16:40.174763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c91125a1aa7'
down_revision = '2a501fcdf5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
