"""Test

Revision ID: 275f1bad180c
Revises: db18367f2a04
Create Date: 2023-11-04 11:17:45.622255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275f1bad180c'
down_revision = 'db18367f2a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('interviewees', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
