"""Test

Revision ID: 2b4f9ae72697
Revises: df9d3d891113
Create Date: 2023-11-01 00:30:07.092328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4f9ae72697'
down_revision = 'df9d3d891113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_whiteboard_assessment_id_assessments', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_whiteboard_question_id_assessments'), 'assessments', ['question_id'], ['id'])
        batch_op.drop_column('assessment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_whiteboard_question_id_assessments'), type_='foreignkey')
        batch_op.create_foreign_key('fk_whiteboard_assessment_id_assessments', 'assessments', ['assessment_id'], ['id'])
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
