"""Updated Interviewee Model

Revision ID: 41c2ff7dcebb
Revises: e5f983a0ba73
Create Date: 2023-10-31 01:37:59.477017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c2ff7dcebb'
down_revision = 'e5f983a0ba73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewees', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
