"""Test

Revision ID: 776a14d0e019
Revises: f51fb220c5a3
Create Date: 2023-11-05 20:23:12.739789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776a14d0e019'
down_revision = 'f51fb220c5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    with op.batch_alter_table('interviewee_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(), nullable=True))

    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('interviewee_assessment', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
