"""Create tables for smart recruiter

Revision ID: 9232c34e43f3
Revises: 
Create Date: 2023-11-10 05:02:12.773967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9232c34e43f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviewees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviewees'))
    )
    op.create_table('invite_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_data'))
    )
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('phoneNumber', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruiters')),
    sa.UniqueConstraint('email', name=op.f('uq_recruiters_email')),
    sa.UniqueConstraint('phoneNumber', name=op.f('uq_recruiters_phoneNumber'))
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], name=op.f('fk_assessments_recruiter_id_recruiters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_table('interviewee_recruiter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interviewee_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interviewee_id'], ['interviewees.id'], name=op.f('fk_interviewee_recruiter_interviewee_id_interviewees')),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], name=op.f('fk_interviewee_recruiter_recruiter_id_recruiters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviewee_recruiter'))
    )
    op.create_table('interviewee_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interviewee_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_status', sa.String(), nullable=True),
    sa.Column('interviewee_status', sa.String(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_interviewee_assessment_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['interviewee_id'], ['interviewees.id'], name=op.f('fk_interviewee_assessment_interviewee_id_interviewees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviewee_assessment'))
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('choices', sa.String(), nullable=True),
    sa.Column('solution', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_questions_assessment_id_assessments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('interviewee_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interviewee_id'], ['interviewees.id'], name=op.f('fk_answers_interviewee_id_interviewees')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answers_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers'))
    )
    op.create_table('whiteboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudocode', sa.String(length=500), nullable=True),
    sa.Column('code', sa.String(length=500), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('interviewee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interviewee_id'], ['interviewees.id'], name=op.f('fk_whiteboard_interviewee_id_interviewees')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_whiteboard_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whiteboard'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whiteboard')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('interviewee_assessment')
    op.drop_table('interviewee_recruiter')
    op.drop_table('assessments')
    op.drop_table('recruiters')
    op.drop_table('invite_data')
    op.drop_table('interviewees')
    # ### end Alembic commands ###
