"""Test

Revision ID: a5b9922a7a1e
Revises: 2b4f9ae72697
Create Date: 2023-11-01 00:30:49.568675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b9922a7a1e'
down_revision = '2b4f9ae72697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.drop_constraint('fk_whiteboard_question_id_assessments', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_whiteboard_question_id_questions'), 'questions', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_whiteboard_question_id_questions'), type_='foreignkey')
        batch_op.create_foreign_key('fk_whiteboard_question_id_assessments', 'assessments', ['question_id'], ['id'])

    # ### end Alembic commands ###
