"""Test

Revision ID: db18367f2a04
Revises: ff8b4ae896b1
Create Date: 2023-11-03 13:07:56.674796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db18367f2a04'
down_revision = 'ff8b4ae896b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewee_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruiter_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('interviewee_status', sa.String(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewee_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('interviewee_status')
        batch_op.drop_column('recruiter_status')

    # ### end Alembic commands ###
