"""Test

Revision ID: e0d335df4c89
Revises: 1c91125a1aa7
Create Date: 2023-10-31 21:26:58.575704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d335df4c89'
down_revision = '1c91125a1aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
